@echo off
echo ============================================
echo    FORCE FRONTEND UPDATE - 100% RELIABLE
echo ============================================
echo.

:: Check if we're in the right directory
if not exist "frontend\package.json" (
    echo ERROR: Must run this from the root project directory
    echo Current directory: %CD%
    pause
    exit /b 1
)

echo Step 1/6: Cleaning old builds...
cd frontend
if exist "dist" rmdir /s /q dist
if exist "node_modules\.vite" rmdir /s /q node_modules\.vite
echo   ✅ Old builds cleaned

echo.
echo Step 2/6: Installing dependencies...
call npm ci
if %ERRORLEVEL% neq 0 (
    echo   ❌ NPM install failed
    pause
    exit /b 1
)
echo   ✅ Dependencies installed

echo.
echo Step 3/6: Building frontend...
call npm run build
if %ERRORLEVEL% neq 0 (
    echo   ❌ Frontend build failed
    pause
    exit /b 1
)
echo   ✅ Frontend built successfully

echo.
echo Step 4/6: Verifying build...
if not exist "dist\index.html" (
    echo   ❌ Build verification failed - no index.html found
    pause
    exit /b 1
)
echo   ✅ Build verified (dist/index.html exists)

cd ..

echo.
echo Step 5/6: Committing to git...
git add .
git commit -m "FRONTEND: Force rebuild - %date% %time%

🔧 Forced frontend rebuild to ensure Railway deployment
- Cleaned old builds and cache
- Fresh npm ci install  
- New frontend build with latest React components
- Built files committed to ensure Railway serves updated frontend

Auto-generated by force_frontend_update.bat

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"

if %ERRORLEVEL% neq 0 (
    echo   ❌ Git commit failed
    pause
    exit /b 1
)
echo   ✅ Changes committed to git

echo.
echo Step 6/6: Pushing to Railway...
git push
if %ERRORLEVEL% neq 0 (
    echo   ❌ Git push failed
    pause
    exit /b 1
)
echo   ✅ Pushed to Railway

echo.
echo ============================================
echo    ✅ FRONTEND UPDATE COMPLETE!
echo ============================================
echo.
echo Next steps:
echo 1. Wait 3-5 minutes for Railway deployment
echo 2. Hard refresh browser (Ctrl+F5)
echo 3. Check for SYNC+ and SCAN buttons
echo.
echo Frontend should now be 100%% updated!
pause